using System.Text;
using System.Web;

namespace SeamQ.Generator.Formatters;

public class HtmlFormatter : IOutputFormatter
{
    public string Format => "html";

    public Task<string> FormatAsync(string markdownContent, string title, CancellationToken cancellationToken = default)
    {
        var htmlBody = ConvertMarkdownToHtml(markdownContent);
        var html = BuildHtmlDocument(title, htmlBody);
        return Task.FromResult(html);
    }

    public string GetFileExtension() => ".html";

    private static string BuildHtmlDocument(string title, string body)
    {
        return $$"""
            <!DOCTYPE html>
            <html lang="en">
            <head>
                <meta charset="UTF-8" />
                <meta name="viewport" content="width=device-width, initial-scale=1.0" />
                <title>{{HttpUtility.HtmlEncode(title)}}</title>
                <style>
                    :root {
                        --bg: #ffffff;
                        --fg: #1a1a2e;
                        --accent: #0f3460;
                        --border: #e0e0e0;
                        --code-bg: #f4f4f8;
                        --table-header-bg: #0f3460;
                        --table-header-fg: #ffffff;
                        --table-stripe: #f9f9fc;
                    }
                    body {
                        font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, sans-serif;
                        line-height: 1.6;
                        max-width: 960px;
                        margin: 2rem auto;
                        padding: 0 1.5rem;
                        color: var(--fg);
                        background: var(--bg);
                    }
                    h1 { border-bottom: 3px solid var(--accent); padding-bottom: 0.5rem; color: var(--accent); }
                    h2 { border-bottom: 1px solid var(--border); padding-bottom: 0.3rem; margin-top: 2rem; }
                    h3 { margin-top: 1.5rem; }
                    table {
                        width: 100%;
                        border-collapse: collapse;
                        margin: 1rem 0;
                        font-size: 0.9rem;
                    }
                    th {
                        background: var(--table-header-bg);
                        color: var(--table-header-fg);
                        padding: 0.6rem 0.8rem;
                        text-align: left;
                    }
                    td {
                        padding: 0.5rem 0.8rem;
                        border: 1px solid var(--border);
                    }
                    tr:nth-child(even) { background: var(--table-stripe); }
                    code {
                        background: var(--code-bg);
                        padding: 0.15rem 0.4rem;
                        border-radius: 3px;
                        font-size: 0.88em;
                    }
                    pre {
                        background: var(--code-bg);
                        padding: 1rem;
                        border-radius: 6px;
                        overflow-x: auto;
                    }
                    pre code {
                        background: none;
                        padding: 0;
                    }
                    .footer {
                        margin-top: 3rem;
                        padding-top: 1rem;
                        border-top: 1px solid var(--border);
                        font-size: 0.85rem;
                        color: #888;
                    }
                </style>
            </head>
            <body>
            {{body}}
            <div class="footer">Generated by SeamQ</div>
            </body>
            </html>
            """;
    }

    /// <summary>
    /// A lightweight markdown-to-HTML converter that handles the subset of markdown
    /// produced by the ICD sections: headings, tables, code blocks, inline code,
    /// bold, italic, and paragraphs.
    /// </summary>
    private static string ConvertMarkdownToHtml(string markdown)
    {
        var sb = new StringBuilder();
        var lines = markdown.Split('\n');
        var inCodeBlock = false;
        var inTable = false;
        var inParagraph = false;
        var tableRowIndex = 0;

        for (var i = 0; i < lines.Length; i++)
        {
            var line = lines[i];

            // Code blocks
            if (line.TrimStart().StartsWith("```"))
            {
                if (inCodeBlock)
                {
                    sb.AppendLine("</code></pre>");
                    inCodeBlock = false;
                }
                else
                {
                    if (inParagraph) { sb.AppendLine("</p>"); inParagraph = false; }
                    if (inTable) { sb.AppendLine("</tbody></table>"); inTable = false; }
                    sb.AppendLine("<pre><code>");
                    inCodeBlock = true;
                }
                continue;
            }

            if (inCodeBlock)
            {
                sb.AppendLine(HttpUtility.HtmlEncode(line));
                continue;
            }

            var trimmed = line.TrimStart();

            // Blank line
            if (string.IsNullOrWhiteSpace(trimmed))
            {
                if (inParagraph) { sb.AppendLine("</p>"); inParagraph = false; }
                if (inTable) { sb.AppendLine("</tbody></table>"); inTable = false; tableRowIndex = 0; }
                continue;
            }

            // Headings
            if (trimmed.StartsWith('#'))
            {
                if (inParagraph) { sb.AppendLine("</p>"); inParagraph = false; }
                if (inTable) { sb.AppendLine("</tbody></table>"); inTable = false; tableRowIndex = 0; }

                var level = 0;
                while (level < trimmed.Length && trimmed[level] == '#') level++;
                if (level >= 1 && level <= 6)
                {
                    var text = trimmed[level..].TrimStart();
                    sb.AppendLine($"<h{level}>{ProcessInline(text)}</h{level}>");
                    continue;
                }
            }

            // Table separator row (e.g., |---|---|)
            if (trimmed.StartsWith('|') && trimmed.Contains("---"))
            {
                // Skip the separator line; it's already handled by the header detection
                continue;
            }

            // Table rows
            if (trimmed.StartsWith('|') && trimmed.EndsWith('|'))
            {
                if (inParagraph) { sb.AppendLine("</p>"); inParagraph = false; }

                var cells = trimmed.Trim('|').Split('|');

                if (!inTable)
                {
                    sb.AppendLine("<table>");
                    sb.AppendLine("<thead><tr>");
                    foreach (var cell in cells)
                    {
                        sb.AppendLine($"<th>{ProcessInline(cell.Trim())}</th>");
                    }
                    sb.AppendLine("</tr></thead>");
                    sb.AppendLine("<tbody>");
                    inTable = true;
                    tableRowIndex = 0;
                }
                else
                {
                    tableRowIndex++;
                    sb.AppendLine("<tr>");
                    foreach (var cell in cells)
                    {
                        sb.AppendLine($"<td>{ProcessInline(cell.Trim())}</td>");
                    }
                    sb.AppendLine("</tr>");
                }
                continue;
            }

            // Close table if a non-table line appears
            if (inTable)
            {
                sb.AppendLine("</tbody></table>");
                inTable = false;
                tableRowIndex = 0;
            }

            // List items
            if (trimmed.StartsWith("- ") || trimmed.StartsWith("* "))
            {
                if (inParagraph) { sb.AppendLine("</p>"); inParagraph = false; }
                sb.AppendLine($"<li>{ProcessInline(trimmed[2..])}</li>");
                continue;
            }

            // Horizontal rule
            if (trimmed is "---" or "***" or "___")
            {
                if (inParagraph) { sb.AppendLine("</p>"); inParagraph = false; }
                sb.AppendLine("<hr />");
                continue;
            }

            // Paragraph text
            if (!inParagraph)
            {
                sb.Append("<p>");
                inParagraph = true;
            }
            else
            {
                sb.Append(' ');
            }
            sb.Append(ProcessInline(trimmed));
        }

        if (inParagraph) sb.AppendLine("</p>");
        if (inTable) sb.AppendLine("</tbody></table>");
        if (inCodeBlock) sb.AppendLine("</code></pre>");

        return sb.ToString();
    }

    /// <summary>
    /// Processes inline markdown: bold, italic, inline code.
    /// </summary>
    private static string ProcessInline(string text)
    {
        var sb = new StringBuilder();
        var i = 0;

        while (i < text.Length)
        {
            // Inline code
            if (text[i] == '`')
            {
                var end = text.IndexOf('`', i + 1);
                if (end > i)
                {
                    sb.Append($"<code>{HttpUtility.HtmlEncode(text[(i + 1)..end])}</code>");
                    i = end + 1;
                    continue;
                }
            }

            // Bold
            if (i + 1 < text.Length && text[i] == '*' && text[i + 1] == '*')
            {
                var end = text.IndexOf("**", i + 2, StringComparison.Ordinal);
                if (end > i)
                {
                    sb.Append($"<strong>{HttpUtility.HtmlEncode(text[(i + 2)..end])}</strong>");
                    i = end + 2;
                    continue;
                }
            }

            // Italic
            if (text[i] == '*')
            {
                var end = text.IndexOf('*', i + 1);
                if (end > i)
                {
                    sb.Append($"<em>{HttpUtility.HtmlEncode(text[(i + 1)..end])}</em>");
                    i = end + 1;
                    continue;
                }
            }

            sb.Append(HttpUtility.HtmlEncode(text[i].ToString()));
            i++;
        }

        return sb.ToString();
    }
}
