namespace SeamQ.Generator.Formatters;

public class MarkdownFormatter : IOutputFormatter
{
    public string Format => "markdown";

    public Task<string> FormatAsync(string markdownContent, string title, CancellationToken cancellationToken = default)
    {
        var header = $"---\ntitle: {title}\ngenerated: {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC\n---\n\n";
        var footer = "\n\n---\n*Generated by SeamQ*\n";
        return Task.FromResult($"{header}{markdownContent}{footer}");
    }

    public string GetFileExtension() => ".md";
}
